# Generated by Django 6.0.1 on 2026-01-21 23:50

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cpf_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[users.utils.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True),
        ),
    ]
