# Generated by Django 6.0.1 on 2026-01-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='forecast',
            field=models.DateField(null=True),
        ),
    ]
